channels:
- conda-forge
dependencies:
- python=3.12.5
- pip<=25.0.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.2
  - numpy==2.2.0
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.0
  - scipy==1.14.1
name: mlflow-env
